### ISSUE TITLE
Raise a "Конец выражения ожидается" error when use "2^2"

### ISSUE THREAD

**Issue by wyman0318** [atastycookie/mathematical-expression-parser#4]
as the title

**Comment by wyman0318** [comment]
If possible, explain the meaning of the error, using translation software is not very understand the meaning of the error

**Comment by atastycookie** [comment]
It looks that tokenization issue, could you try as a workaround send the backstrace/log/output for the `(2^2)`

**Comment by wyman0318** [comment]
"(2^2)" will raise the error "п роп ена закрываю ц ая скобка"

**Comment by wyman0318** [comment]
Traceback (most recent call last):
  File "E:/src/yww/YikeFDTDBook/YikeSim/src/gui/win/deluxe_win/left_manager/global_custom_manager/cal.py", line 442, in <module>
    print(calc.evalute("2^2"))
  File "E:/src/yww/YikeFDTDBook/YikeSim/src/gui/win/deluxe_win/left_manager/global_custom_manager/cal.py", line 435, in evalute
    self.send_error(3)
  File "E:/src/yww/YikeFDTDBook/YikeSim/src/gui/win/deluxe_win/left_manager/global_custom_manager/cal.py", line 355, in send_error
    raise TCalcException("Конец выражения ожидается")
__main__.TCalcException: Конец выражения ожидается

**Comment by wyman0318** [comment]
like this？
`Traceback (most recent call last):
  line 442, in <module>
    print(calc.evalute("2^2"))
line 435, in evalute
    self.send_error(3)
 line 355, in send_error
    raise TCalcException("Конец выражения ожидается")
__main__.TCalcException: Конец выражения ожидается`

**Comment by wyman0318** [comment]
like this？

> Traceback (most recent call last):
  line 442, in <module>
    print(calc.evalute("2^2"))
   line 435, in evalute
    self.send_error(3)
  line 355, in send_error
    raise TCalcException("Конец выражения ожидается")
__main__.TCalcException: Конец выражения ожидается
